"""
ai/generate_sql.py

Takes a natural-language question + the table schema, asks Groq
for a SQL query, and cleans up the raw response (LLMs sometimes wrap
code in markdown fences even when told not to -- we strip that
defensively rather than trusting the instruction alone).
"""

import re
from ai.llm_client import ask_llm
from ai.prompts import build_sql_prompt


class NoQueryPossibleError(Exception):
    """Raised when the LLM determines the question can't be answered from this data."""
    pass


def _strip_markdown_fences(text: str) -> str:
    """Removes ```sql ... ``` or ``` ... ``` wrapping if the model added it anyway."""
    text = text.strip()
    text = re.sub(r"^```(?:sql)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*```$", "", text)
    return text.strip()


def generate_sql(question: str, schema_text: str) -> str:
    """
    Returns a raw (not yet validated) SQL string generated by the LLM.
    Validation happens separately in utils/validator.py -- this
    function's only job is turning English into a SQL string.
    """
    prompt = build_sql_prompt(question, schema_text)
    raw_response = ask_llm(prompt, temperature=0.2)
    sql = _strip_markdown_fences(raw_response)

    if sql.strip().upper() == "NO_QUERY_POSSIBLE":
        raise NoQueryPossibleError(
            "That question can't be answered from the uploaded data's columns."
        )

    return sql
